- debug:
    msg: "BUILT COMMAND: {{ ping_command }} {{ hostvars[item].inventory_hostname}}"
  with_items: "{{ groups['targets'] }}"
  
- name: TELNET TEST
  shell: "{{ ping_command }} {{ hostvars[item] }}"
  with_items: "{{ groups['targets'] }}"
  register: command_output
  ignore_errors: yes
  no_log: false
  changed_when: false
  



