- debug:
    msg: "BUILT COMMAND: {{ ping_command }} {{ hostvars[item].inventory_hostname.split('/')[0] }}"
  with_items: "{{ groups['targets'] }}"
  
- name: PING TEST
  shell: "{{ ping_command }} {{ hostvars[item].inventory_hostname.split('/')[0] }}"
  with_items: "{{ groups['targets'] }}"
  register: command_output
  ignore_errors: yes
  no_log: false
  changed_when: false
  tags: check
  
- name: MODULE PING TEST
  ansible.netcommon.net_ping:
    dest: "{{ hostvars[item].inventory_hostname }}"
  with_items: "{{ groups['targets'] }}"
  tags: check
  



