- debug:
    msg: "BUILT COMMAND: {{ traceroute_command }} {{ hostvars[item].inventory_hostname}}"
  with_items: "{{ groups['targets'] }}"
  
- name: TRACEROUTE TEST
  shell: "{{ traceroute_command }} {{ hostvars[item].inventory_hostname}}"
  with_items: "{{ groups['targets'] }}"
  register: command_output
  ignore_errors: yes
  no_log: false
  changed_when: false
